# -*- coding: utf-8 -*-
"""TRABALHO 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10t6v24MIjMgBBw0923gnWpjGaWRtC9GF
"""

# Coffee Shops Tia Rosa - Sistema Simples de Gerenciamento

produtos = []
clientes = []
pedidos = []

def cadastrar_produtos():
    # Ensure consistent indentation (e.g., 4 spaces) for all lines within the function
    nome = input("nome do produto:")
    preco = float(input("Preço do produto (R$): "))
    descricao = input("Descrição do produto: ")
    produto = {"nome": nome, "preco": preco, "descricao": descricao}
    produtos.append(produto)
    print("Produto cadastrado com sucesso!\n")

def listar_produtos():
    if not produtos:
        print("Nenhum produto cadastrado.\n")
    else:
        print("=== CARDÁPIO ===")
        for i, p in enumerate(produtos):
            print(f"{i + 1}. {p['nome']} - R$ {p['preco']:.2f}")
            print(f"   Descrição: {p['descricao']}\n")

def cadastrar_cliente():
    nome = input("Nome do cliente: ")
    telefone = input("Telefone: ")
    cliente = {"nome": nome, "telefone": telefone}
    clientes.append(cliente)
    print("Cliente cadastrado com sucesso!\n")

def fazer_pedido():
    if not produtos:
        print("Nenhum produto disponível para pedido.\n")
        return
    nome_cliente = input("Nome do cliente: ")
    listar_produtos()
    escolha = int(input("Digite o número do produto desejado: ")) - 1
    if 0 <= escolha < len(produtos):
        pedido = {
            "cliente": nome_cliente,
            "produto": produtos[escolha]["nome"],
            "valor": produtos[escolha]["preco"]
        }
        pedidos.append(pedido)
        print("Pedido realizado com sucesso!\n")
    else:
        print("Produto inválido.\n")

def relatorio_vendas():
    if not pedidos:
        print("Nenhuma venda registrada.\n")
        return
    total = 0
    print("=== RELATÓRIO DE VENDAS ===")
    for p in pedidos:
        print(f"Cliente: {p['cliente']} - Produto: {p['produto']} - R$ {p['valor']:.2f}")
        total += p['valor']
    print(f"Total em vendas: R$ {total:.2f}\n")

def menu():
    while True:
        print("=== COFFEE SHOPS TIA ROSA ===")
        print("1. Cadastrar produto")
        print("2. Listar produtos")
        print("3. Cadastrar cliente")
        print("4. Fazer pedido")
        print("5. Relatório de vendas")
        print("6. Sair")
        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            # Correct the function call from cadastrar_produto to cadastrar_produtos
            cadastrar_produtos()
        elif opcao == "2":
            listar_produtos()
        elif opcao == "3":
            cadastrar_cliente()
        elif opcao == "4":
            fazer_pedido()
        elif opcao == "5":
            relatorio_vendas()
        elif opcao == "6":
            print("Encerrando o sistema... Obrigado!")
            break
        else:
            print("Opção inválida.\n")

# Inicia o sistema
menu()